sudo: required

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
    - eval "${MATRIX_EVAL}"


before_install:
  - sudo apt-get install libhdf5-dev
  - sudo apt-get install libnetcdf-dev
  
# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc-6
  
# Build steps
script:
  - mkdir build
  - cd build
  - CC=gcc-6 CXX=g++-6 ${DEPS_DIR}/cmake/bin/cmake -DEIGEN3_INCLUDES=${DEPS_DIR}/eigen -DBUILD_WITH_PYBIND11=ON -DPYTHON_EXECUTABLE=$(python-config --prefix)/bin/python3.5  .. && make
