# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pool:
  vmImage: 'VS2017'

variables:
  buildPlatform: 'x64'
  buildConfiguration: 'Release'

steps:
- checkout: https://github.com/Microsoft/vcpkg.git

- checkout: https://github.com/aglowacki/XRF-Maps.git
    submodules: true | recursive

- script: |
     cd vcpkg
     bootstrap-vcpkg.bat
     vcpkg install hdf5 netcdf-c cppzmq  qt5-base qt5-charts 

- script: |
    mkdir build
    cd build
  displayName: 'make build directory'

- task: CMake@1
  inputs:
    workingDirectory: 'build'
    cmakeArgs: -G "Visual Studio 15 2017 Win64" ..

- script: nmake
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
