trigger:
  - master
variables:
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  VCPKG_DEFAULT_TRIPLET: 'x64-windows'
jobs:
  - job: Default
    timeoutInMinutes: 360
    cancelTimeoutInMinutes: 180
    pool:
      vmImage: 'windows-latest'    
    steps:
    - checkout: self
      submodules: true
    - script: .\vcpkg\bootstrap-vcpkg.bat
    - task: Cache@2
      inputs:
        key: mykey | mylockfile
        restoreKeys: mykey
        path: $(Pipeline.Workspace)/vcpkg/installed
        cacheHitVar: CACHE_RESTORED
    - script: .\vcpkg\vcpkg.exe install hdf5 netcdf-c yaml-cpp zeromq jsoncpp --triplet x64-windows
      condition: ne(variables.CACHE_RESTORED, 'true')
    - task: Cache@2
      inputs:
        key: mykey 
        path: $(Pipeline.Workspace)/vcpkg/installed
    - script: mkdir build
    - task: CMake@1
      inputs:
        workingDirectory: 'build'
        cmakeArgs: '-G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DBUILD_WITH_QT=OFF -DBUILD_WITH_ZMQ=ON -DAVX2=ON ..'
    - task: MSBuild@1
      inputs:
        solution: 'build/ALL_BUILD.vcxproj'
        maximumCpuCount: true
        platform: 'x64'
    - task: CopyFiles@2
      displayName: 'Copy bin Files to install'
      inputs:
        SourceFolder: $(System.DefaultWorkingDirectory)/bin
        TargetFolder: $(System.DefaultWorkingDirectory)/install/bin
    - task: CopyFiles@2
      displayName: 'Copy ref Files to install'
      inputs:
        SourceFolder: $(System.DefaultWorkingDirectory)/reference
        TargetFolder: $(System.DefaultWorkingDirectory)/install/reference
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/install/
        artifactName: XRF-Maps
