trigger:
  - master
variables:
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  VCPKG_DEFAULT_TRIPLET: 'x64-windows'
jobs:
  - job: Default
    timeoutInMinutes: 360
    cancelTimeoutInMinutes: 180
    pool:
      vmImage: 'windows-latest'    
    steps:
    - checkout: self
      submodules: true
    - script: .\vcpkg\bootstrap-vcpkg.bat
    - script: echo set(VCPKG_BUILD_TYPE release)>>vcpkg\triplets\x64-windows.cmake
    - script: .\vcpkg\vcpkg.exe install hdf5 netcdf-c yaml-cpp zeromq --triplet x64-windows
    - script: mkdir build
    - task: CMake@1
      inputs:
        workingDirectory: 'build'
        cmakeArgs: '-G "Visual Studio 16 2019" -A x64 -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DBUILD_WITH_QT=OFF -DBUILD_WITH_ZMQ=ON ..'
    - task: MSBuild@1
      inputs:
        solution: 'build/ALL_BUILD.vcxproj'
        maximumCpuCount: true
        platform: 'x64'
