trigger:
  - master
variables:
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  VCPKG_DEFAULT_TRIPLET: 'x64-windows'
jobs:
  - job: Default
    timeoutInMinutes: 360
    cancelTimeoutInMinutes: 180
    pool:
      vmImage: 'windows-latest'    
    steps:
    - checkout: self
      submodules: true
    - powershell: |
        $Webclient = New-Object net.webclient
        $Webclient.Downloadfile("https://anl.box.com/shared/static/f07vdq5c082hl9tpm3luagaletwrjpc0.zip", "vcpkg.zip") 
        $progressPreference = 'SilentlyContinue'
        Expand-Archive -Force -Path .\vcpkg.zip -DestinationPath .\
    - script: mkdir build
    - task: CMake@1
      inputs:
        workingDirectory: 'build'
        cmakeArgs: '-G "Visual Studio 16 2019" -A x64 -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DBUILD_WITH_QT=ON -DBUILD_WITH_ZMQ=ON ..'
    - task: MSBuild@1
      inputs:
        solution: 'build/ALL_BUILD.vcxproj'
        maximumCpuCount: true
        platform: 'x64'
