trigger:
  - master
variables:
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  VCPKG_DEFAULT_TRIPLET: 'x64-windows'
jobs:
  - job: Default
    timeoutInMinutes: 360
    cancelTimeoutInMinutes: 180
    pool:
      vmImage: 'windows-latest'    
    steps:
    - checkout: self
      submodules: true
    - powershell: |
        $Webclient = New-Object net.webclient
        $Webclient.Downloadfile("http://anl.box.com/shared/static/z2ckxkdvejoakg1do2e5c4x6zfva51qk.zip", "vcpkg.zip")
        $progressPreference = 'SilentlyContinue'
        Expand-Archive -Force -Path .\vcpkg.zip -DestinationPath .\
    - script: mkdir build
    - task: CMake@1
      inputs:
        workingDirectory: 'build'
        cmakeArgs: '-G "Visual Studio 16 2019" -A x64 -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DBUILD_WITH_QT=ON -DBUILD_WITH_ZMQ=ON ..'
    - task: MSBuild@1
      inputs:
        solution: 'build/ALL_BUILD.vcxproj'
        maximumCpuCount: true
        platform: 'x64'
    - script: |
        xcopy vcpkg\installed\x64-windows\bin\*.dll .\bin /s /y
    - script: |
        cd bin
        .\xrf_maps.exe 
